'use client'
import NextImage from 'next/image'
import FeatureCard from '@/components/ui/FeatureCard';
import TestimonialCard from '@/components/ui/TestimonialCard';
import { FileText, BarChart2, Users, CheckCircle, Twitter, Facebook, Instagram } from 'lucide-react';  

export default function HomePage() {  
  return (  
    <div className="bg-gray-50">  
      {/* Hero Section */}  
      <section className="relative bg-gradient-to-r from-indigo-600 to-purple-600 text-white">  
        <div className="mobile-container py-12 sm:py-16 lg:py-20 text-center sm:text-left">
          <div className="flex items-center justify-center mb-6 sm:mb-8">
            <NextImage src="/logo.svg"
              alt="AI Content Platform" 
              width={64}
              height={64}
              className="w-12 h-12 sm:w-16 sm:h-16 rounded-full object-cover"
              priority
            />
          </div>  
          <h1 className="mobile-heading font-extrabold leading-tight mb-4 sm:mb-6">  
            Revolutionize Your Content Management  
          </h1>  
          <p className="mobile-text text-gray-200 mb-4">  
            AI-powered tools to create, manage, and analyze your content with ease.  
            This Project has two parts:
          </p>
          <ul className="mobile-text text-gray-200 list-disc list-inside mb-4 space-y-1">
            <li>1. A blog website</li>
            <li>2. A content management system</li>
          </ul>
          <p className="mobile-text text-gray-200 mb-6 sm:mb-8">
            The content in blog is generated by AI using our other project called "AI Content Generator"
          </p>  
          <div className="mobile-space flex flex-col sm:flex-row justify-center sm:justify-start">  
            <a target='_blank' href="/dashboard" rel="noopener noreferrer" className="mb-4 sm:mb-0">  
              <button className="mobile-button w-full sm:w-auto bg-white text-indigo-600 font-semibold rounded-lg shadow-lg hover:bg-gray-100 transition-all duration-200">  
                View AI Content Generator
              </button>  
            </a>  
            <a href="https://blogg-ed.vercel.app/" target="_blank" rel="noopener noreferrer">  
              <button className="mobile-button w-full sm:w-auto bg-indigo-700 text-white font-semibold rounded-lg shadow-lg hover:bg-indigo-800 transition-all duration-200">  
                View Our Blog website 
              </button>  
            </a>  
          </div>  
        </div>   
      </section>  

      {/* Features Section */}  
      <section className="mobile-container py-12 sm:py-16 lg:py-20">  
        <h2 className="mobile-heading font-bold text-center text-gray-800 mb-4">Features</h2>  
        <p className="mobile-text text-center text-gray-600 mb-8 sm:mb-12">  
          Everything you need to create, manage, and grow your content.  
        </p>  
        <div className="mobile-grid gap-6 sm:gap-8">  
          <FeatureCard  
            icon={FileText}  
            title="Content Creation"  
            description="AI-powered tools to help you create engaging content effortlessly."  
          />  
          <FeatureCard  
            icon={BarChart2}  
            title="Analytics Dashboard"  
            description="Track your content's performance with real-time analytics."  
          />  
          <FeatureCard  
            icon={Users}  
            title="Collaboration"  
            description="Work with your team in real-time with collaborative editing."  
          />  
        </div>  
      </section>  

      {/* Testimonials Section */}  
      <section className="bg-gray-100 py-12 sm:py-16 lg:py-20">  
        <div className="mobile-container">  
          <h2 className="mobile-heading font-bold text-center text-gray-800 mb-8 sm:mb-12">What Our Users Say</h2>  
          <div className="mobile-grid gap-6 sm:gap-8">  
            <TestimonialCard  
              name="Jane Doe"  
              role="Content Strategist"  
              feedback="This platform has completely transformed the way I manage my content. The AI tools are a game-changer!"  
            />  
            <TestimonialCard  
              name="John Smith"  
              role="Marketing Manager"  
              feedback="The analytics dashboard is incredibly insightful. I can track everything in one place!"  
            />  
            <TestimonialCard  
              name="Emily Johnson"  
              role="Freelance Writer"  
              feedback="Collaborating with my clients has never been easier. Highly recommend this platform!"  
            />  
          </div>  
        </div>  
      </section>  

      {/* Footer */}  
      <footer className="bg-gray-800 text-white py-8 sm:py-12">  
        <div className="mobile-container flex flex-col sm:flex-row justify-between items-center space-y-4 sm:space-y-0">  
          <p className="mobile-text-sm">&copy; 2024 AI Content Platform. All rights reserved.</p>  
          <div className="flex space-x-4">  
            <a href="#" className="text-gray-400 hover:text-white transition-colors duration-200 touch-target">  
              <Twitter className="h-5 w-5" />  
            </a>  
            <a href="#" className="text-gray-400 hover:text-white transition-colors duration-200 touch-target">  
              <Facebook className="h-5 w-5" />  
            </a>  
            <a href="#" className="text-gray-400 hover:text-white transition-colors duration-200 touch-target">  
              <Instagram className="h-5 w-5" />  
            </a>  
          </div>  
        </div>  
      </footer>  
    </div>  
  );  
}  
